version: '3.4'

services:
  contact.api:
    image: ${DOCKER_REGISTRY-}contact
    build:
      context: .
      dockerfile: Contact.API/Dockerfile
      ports: - 7000:7000
      networks: - int_net
      

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
      ports: -80:80
      networks: - micro_net


  reservationapi:
    image: ${DOCKER_REGISTRY-}reservationapi
    build:
      context: .
      dockerfile: ReservationAPI/Dockerfile
      ports: - 9000:9000
      networks: - int_net




    networks:
        int_net:
            driver:overlay
            internal:true
        micro_net:
            driver:bridge
